"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config,Csv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+g44lr(gnd1lo9@*rxtj!9^wh3&_05e259xsnbk%r6vw$9yww='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG",True)
ALLOWED_HOSTS =  config("ALLOWED_HOSTS","*",cast=Csv())
CSRF_TRUSTED_ORIGINS = [f"http://{host}" for host in ALLOWED_HOSTS] + [f"https://{host}" for host in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',
    'front'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': str(config('DJANGO_DB_NAME')),
        'USER': str(config('DJANGO_DB_USER')),
        'PASSWORD': str(config('DJANGO_DB_PASSWORD')),
        'HOST': "localhost",
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_FILE_ROOT = 'constance'
CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {'required': False}],
    'email_field': ['django.forms.EmailField', {}],
}

CONSTANCE_CONFIG = {
    # Basic Information
    'name': ('Creative', 'The name of your company'),
    'short_description': ('Description courte', "Brief description of the company"),
    'about_the_company': ('Description', "Description of the company"),
    'meta_description': ('', "Description for search engines"),
    'brand_url': ('https://www.creators.cc', "Website URL"),

    # Contact Information
    'mail': ('creative@creative.com', 'Your professional email', 'email_field'),
    'phone': ('+213770000000', 'Your professional phone number'),
    'adresse': ('Algeria', "Company's address"),

    # Visual Elements
    'logo': ("", "Company's logo", 'image_field'),
    'theme_color': ('#8dc04d', "Theme color"),
    'about_image': ("", "Image for the about page", 'image_field'),
    'fav_icon': ('', "Website's favicon", 'image_field'),

    # Analytics
    'google_analytics_tag': ('UA-xxxxxxxx-1', "Google Analytics tag"),
    'GOOGLE_RECAPTCHA_SITE_KEY': ('', "your reCAPTCHA SITE key"),
    'GOOGLE_RECAPTCHA_SECRET_SITE_KEY': ('', "your reCAPTCHA secret key"),
}

CONSTANCE_CONFIG_FIELDSETS = {
    # Informations générales
    'General information': (
        'name',
        'logo',
        'about_image',
        'theme_color',
        'brand_url',
        'meta_description',
        'fav_icon',
    ),

    # Contact information
    'Contact information': (
        'mail',
        'phone',
        'adresse',
    ),

    # Company information
    'Company information': (
        'about_the_company',
        'short_description',
    ),

    # Company information
    'Google information': (
        'google_analytics_tag',
        'GOOGLE_RECAPTCHA_SITE_KEY',
        'GOOGLE_RECAPTCHA_SECRET_SITE_KEY',
    ),
}


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
